# Generated by Django 6.0 on 2025-12-16 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('unidade_medida', models.CharField(choices=[('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('UN', 'Unidade')], max_length=30)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('produto', models.ManyToManyField(blank=True, to='estoque.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('materia_prima', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estoque.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=0)),
                ('tipo_movimentacao', models.CharField(choices=[('COMPRA', 'Entrada por Compra'), ('AJUSTE_POS', 'Ajuste Positivo/Inventário'), ('DEVOLUCAO', 'Devolução de Venda/Cliente'), ('VENDA', 'Saída por Venda/Consumo'), ('AJUSTE_NEG', 'Ajuste Negativo/Perda'), ('TRANSFERENCIA', 'Transferência (se houver locais de estoque)')], max_length=20)),
                ('data_movimentacao', models.DateTimeField(auto_now=True)),
                ('estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.estoque')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.materiaprima')),
            ],
        ),
    ]
