# Generated by Django 6.0 on 2025-12-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='CustoProducao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custo_material', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_operacional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venda.venda')),
            ],
        ),
    ]
