# Generated by Django 6.0 on 2025-12-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custoproducao',
            options={'verbose_name': 'Custo de Produção', 'verbose_name_plural': 'Custos de Produção'},
        ),
    ]
