# Generated by Django 6.0 on 2025-12-16 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('PIZZA_CLASSICA', 'Pizzas Clássicas'), ('PIZZA_ESPECIAL', 'Pizzas Especiais'), ('ESFIHA', 'Esfihas e Salgados'), ('PRODUCAO_DOCE', 'Sobremesas de Produção'), ('REFRIGERANTE', 'Refrigerantes'), ('CERVEJA', 'Cervejas'), ('SUCO_AGUA', 'Sucos e Águas'), ('REVENDA_DOCE', 'Sobremesas Industrializadas'), ('ADICIONAL', 'Adicionais de Sabor'), ('COMBO', 'Combos e Promoções')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicaoProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_prima', to='estoque.materiaprima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.produto')),
            ],
        ),
    ]
