# Generated by Django 6.0 on 2025-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, default='Insira seu endereço completo', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, default=' (00)00000-0000', max_length=15, null=True),
        ),
    ]
